# Generated by Django 2.2.2 on 2019-06-13 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190611_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wearings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fly', models.CharField(choices=[('Y', 'Yeah, it was fly'), ('N', 'Not my flyest, but still fy')], default='Y', max_length=1)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Shoe')),
            ],
        ),
    ]
