# Generated by Django 2.2.2 on 2019-06-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_wearings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wearings',
            name='date',
            field=models.DateField(verbose_name='worn on date'),
        ),
    ]
